export default {
  out: '.header button',
  start: '.text-center>button',
  personName: '.players:nth-child(1)>p',
  personLife: '.players:nth-child(1)>div:not(.progress)',
  monsterLife: '.players:nth-child(2)>div:not(.progress)',
  statusGame: { el: 'button', text: 'INICIAR NOVO JOGO' },
  btnAtk: { el: 'button', text: 'ATAQUE' },
  btnSkill: { el: 'button', text: 'HABILIDADE' },
  btnHeal: { el: 'button', text: 'CURA' },
  btnAuto: { el: 'button', text: 'Auto Game' },
  btnStop: { el: 'button', text: 'Stop' },
  btnDesist: { el: 'button', text: 'DESISTIR' },
  events: '.box li',
  eventPerson: '.box>ul .jogador>strong:nth-child(1)',
  eventMonster: '.box>ul .monster>strong:nth-child(2)',
  eventHeal: '.box>ul .cura strong:nth-child(1)',
}